// @flow

export const LOGIN = 'LOGIN'
export const LOGIN_BY_PHONE = 'LOGIN_BY_PHONE'

export const GET_PHOTOS ='GET_PHOTOS'

export const OPEN_PREVIEW_PHOTO_DIALOG = 'OPEN_PREVIEW_PHOTO_DIALOG'
export const CLOSE_PREVIEW_PHOTO_DIALOG = 'CLOSE_PREVIEW_PHOTO_DIALOG'

export const LOGOUT = 'LOGOUT'
